// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services/CardsActuelles.tsx": () => import("../components/mockups/services/CardsActuelles.tsx"),
  "./components/mockups/services/Forfaits.tsx": () => import("../components/mockups/services/Forfaits.tsx")
};
